mv  A03.filtered  A03.filtered.A07
mv  BRO.filtered  BRO.filtered.A07
mv  CCA.filtered  CCA.filtered.A07
mv  CCB.filtered  CCB.filtered.A07
mv  CFv4.filtered  CFv4.filtered.A07
mv  CXA.filtered  CXA.filtered.A07
mv  CXB.filtered  CXB.filtered.A07
mv  ECD04.filtered  ECD04.filtered.A07
mv  LongYou.filtered  LongYou.filtered.A07
mv  MIZ.filtered  MIZ.filtered.A07
mv  OIB.filtered  OIB.filtered.A07
mv  PCA.filtered  PCA.filtered.A07
mv  PCB.filtered  PCB.filtered.A07
mv  PCC.filtered  PCC.filtered.A07
mv  PCD.filtered  PCD.filtered.A07
mv  PCE.filtered  PCE.filtered.A07
mv  TCA.filtered  TCA.filtered.A07
mv  TUA.filtered  TUA.filtered.A07
mv  TUB.filtered  TUB.filtered.A07
mv  TUE.filtered  TUE.filtered.A07
mv  Z1v2.filtered  Z1v2.filtered.A07
