mv  A03.filtered  A03.filtered.A02
mv  BRO.filtered  BRO.filtered.A02
mv  CCA.filtered  CCA.filtered.A02
mv  CCB.filtered  CCB.filtered.A02
mv  CFv4.filtered  CFv4.filtered.A02
mv  CXA.filtered  CXA.filtered.A02
mv  CXB.filtered  CXB.filtered.A02
mv  ECD04.filtered  ECD04.filtered.A02
mv  LongYou.filtered  LongYou.filtered.A02
mv  MIZ.filtered  MIZ.filtered.A02
mv  OIB.filtered  OIB.filtered.A02
mv  PCA.filtered  PCA.filtered.A02
mv  PCB.filtered  PCB.filtered.A02
mv  PCC.filtered  PCC.filtered.A02
mv  PCD.filtered  PCD.filtered.A02
mv  PCE.filtered  PCE.filtered.A02
mv  TCA.filtered  TCA.filtered.A02
mv  TUA.filtered  TUA.filtered.A02
mv  TUB.filtered  TUB.filtered.A02
mv  TUE.filtered  TUE.filtered.A02
mv  Z1v2.filtered  Z1v2.filtered.A02
