mv  A03.filtered  A03.filtered.A08
mv  BRO.filtered  BRO.filtered.A08
mv  CCA.filtered  CCA.filtered.A08
mv  CCB.filtered  CCB.filtered.A08
mv  CFv4.filtered  CFv4.filtered.A08
mv  CXA.filtered  CXA.filtered.A08
mv  CXB.filtered  CXB.filtered.A08
mv  ECD04.filtered  ECD04.filtered.A08
mv  LongYou.filtered  LongYou.filtered.A08
mv  MIZ.filtered  MIZ.filtered.A08
mv  OIB.filtered  OIB.filtered.A08
mv  PCA.filtered  PCA.filtered.A08
mv  PCB.filtered  PCB.filtered.A08
mv  PCC.filtered  PCC.filtered.A08
mv  PCD.filtered  PCD.filtered.A08
mv  PCE.filtered  PCE.filtered.A08
mv  TCA.filtered  TCA.filtered.A08
mv  TUA.filtered  TUA.filtered.A08
mv  TUB.filtered  TUB.filtered.A08
mv  TUE.filtered  TUE.filtered.A08
mv  Z1v2.filtered  Z1v2.filtered.A08
