mv  A03.filtered  A03.filtered.A01
mv  BRO.filtered  BRO.filtered.A01
mv  CCA.filtered  CCA.filtered.A01
mv  CCB.filtered  CCB.filtered.A01
mv  CFv4.filtered  CFv4.filtered.A01
mv  CXA.filtered  CXA.filtered.A01
mv  CXB.filtered  CXB.filtered.A01
mv  ECD04.filtered  ECD04.filtered.A01
mv  LongYou.filtered  LongYou.filtered.A01
mv  MIZ.filtered  MIZ.filtered.A01
mv  OIB.filtered  OIB.filtered.A01
mv  PCA.filtered  PCA.filtered.A01
mv  PCB.filtered  PCB.filtered.A01
mv  PCC.filtered  PCC.filtered.A01
mv  PCD.filtered  PCD.filtered.A01
mv  PCE.filtered  PCE.filtered.A01
mv  TCA.filtered  TCA.filtered.A01
mv  TUA.filtered  TUA.filtered.A01
mv  TUB.filtered  TUB.filtered.A01
mv  TUE.filtered  TUE.filtered.A01
mv  Z1v2.filtered  Z1v2.filtered.A01
