mv  A03.filtered  A03.filtered.A05
mv  BRO.filtered  BRO.filtered.A05
mv  CCA.filtered  CCA.filtered.A05
mv  CCB.filtered  CCB.filtered.A05
mv  CFv4.filtered  CFv4.filtered.A05
mv  CXA.filtered  CXA.filtered.A05
mv  CXB.filtered  CXB.filtered.A05
mv  ECD04.filtered  ECD04.filtered.A05
mv  LongYou.filtered  LongYou.filtered.A05
mv  MIZ.filtered  MIZ.filtered.A05
mv  OIB.filtered  OIB.filtered.A05
mv  PCA.filtered  PCA.filtered.A05
mv  PCB.filtered  PCB.filtered.A05
mv  PCC.filtered  PCC.filtered.A05
mv  PCD.filtered  PCD.filtered.A05
mv  PCE.filtered  PCE.filtered.A05
mv  TCA.filtered  TCA.filtered.A05
mv  TUA.filtered  TUA.filtered.A05
mv  TUB.filtered  TUB.filtered.A05
mv  TUE.filtered  TUE.filtered.A05
mv  Z1v2.filtered  Z1v2.filtered.A05
