mv  A03.filtered  A03.filtered.A10
mv  BRO.filtered  BRO.filtered.A10
mv  CCA.filtered  CCA.filtered.A10
mv  CCB.filtered  CCB.filtered.A10
mv  CFv4.filtered  CFv4.filtered.A10
mv  CXA.filtered  CXA.filtered.A10
mv  CXB.filtered  CXB.filtered.A10
mv  ECD04.filtered  ECD04.filtered.A10
mv  LongYou.filtered  LongYou.filtered.A10
mv  MIZ.filtered  MIZ.filtered.A10
mv  OIB.filtered  OIB.filtered.A10
mv  PCA.filtered  PCA.filtered.A10
mv  PCB.filtered  PCB.filtered.A10
mv  PCC.filtered  PCC.filtered.A10
mv  PCD.filtered  PCD.filtered.A10
mv  PCE.filtered  PCE.filtered.A10
mv  TCA.filtered  TCA.filtered.A10
mv  TUA.filtered  TUA.filtered.A10
mv  TUB.filtered  TUB.filtered.A10
mv  TUE.filtered  TUE.filtered.A10
mv  Z1v2.filtered  Z1v2.filtered.A10
