mv  A03.filtered  A03.filtered.A04
mv  BRO.filtered  BRO.filtered.A04
mv  CCA.filtered  CCA.filtered.A04
mv  CCB.filtered  CCB.filtered.A04
mv  CFv4.filtered  CFv4.filtered.A04
mv  CXA.filtered  CXA.filtered.A04
mv  CXB.filtered  CXB.filtered.A04
mv  ECD04.filtered  ECD04.filtered.A04
mv  LongYou.filtered  LongYou.filtered.A04
mv  MIZ.filtered  MIZ.filtered.A04
mv  OIB.filtered  OIB.filtered.A04
mv  PCA.filtered  PCA.filtered.A04
mv  PCB.filtered  PCB.filtered.A04
mv  PCC.filtered  PCC.filtered.A04
mv  PCD.filtered  PCD.filtered.A04
mv  PCE.filtered  PCE.filtered.A04
mv  TCA.filtered  TCA.filtered.A04
mv  TUA.filtered  TUA.filtered.A04
mv  TUB.filtered  TUB.filtered.A04
mv  TUE.filtered  TUE.filtered.A04
mv  Z1v2.filtered  Z1v2.filtered.A04
