mv  A03.filtered  A03.filtered.A06
mv  BRO.filtered  BRO.filtered.A06
mv  CCA.filtered  CCA.filtered.A06
mv  CCB.filtered  CCB.filtered.A06
mv  CFv4.filtered  CFv4.filtered.A06
mv  CXA.filtered  CXA.filtered.A06
mv  CXB.filtered  CXB.filtered.A06
mv  ECD04.filtered  ECD04.filtered.A06
mv  LongYou.filtered  LongYou.filtered.A06
mv  MIZ.filtered  MIZ.filtered.A06
mv  OIB.filtered  OIB.filtered.A06
mv  PCA.filtered  PCA.filtered.A06
mv  PCB.filtered  PCB.filtered.A06
mv  PCC.filtered  PCC.filtered.A06
mv  PCD.filtered  PCD.filtered.A06
mv  PCE.filtered  PCE.filtered.A06
mv  TCA.filtered  TCA.filtered.A06
mv  TUA.filtered  TUA.filtered.A06
mv  TUB.filtered  TUB.filtered.A06
mv  TUE.filtered  TUE.filtered.A06
mv  Z1v2.filtered  Z1v2.filtered.A06
